export enum ACTION_TYPES {
	FETCH_LIST='@@WEATHER/FETCH_LIST',
	FETCH_NEW_CITY='@@WEATHER/FETCH_NEW_CITY',
	SET_LIST='@@WEATHER/SET_LIST',
	DELETE_CITY='@@WEATHER/DELETE_CITY',
	ADD_CITY='@@WEATHER/ADD_CITY',
	SET_CITY='@@WEATHER/SET_CITY',
}